### ISSUE TITLE
Generate COMOS like mocks from kappaTNG

### ISSUE THREAD

**Issue by liuxx479** [CosmoStat/jax-lensing#10]
Using the selected Pz from [Prepare COSMOS redshift distribution](https://github.com/CosmoStat/jax-lensing/issues/9)
kappaTNG: http://www.columbialensing.org/#tng

**Comment by liuxx479** [comment]
Sample map using the weights calculated for [COSMOS pz](https://github.com/CosmoStat/jax-lensing/issues/9)

![Screen Shot 2020-12-07 at 10 37 14 AM](https://user-images.githubusercontent.com/2658222/101391296-f73af800-3878-11eb-88f4-6137b14af7f0.jpg)

**Comment by EiffL** [comment]
It's looking good :-)

**Comment by liuxx479** [comment]
Files are produced here (on Cori):
`/global/cscratch1/sd/jialiu/kappaTNG/COSMOS/`
Each map is 1024x1024 pixels, 5x5 deg^2, so resolution ~ 0.3 arcmin/pix
File format: .npy, can load with `np.load(filename)`

Code to generate these files:
https://github.com/liuxx479/pzCOSMOS/blob/main/kappaTNG_COSMOS.py
(tests/plots: https://github.com/liuxx479/pzCOSMOS/blob/main/kappaTNG_COSMOS.ipynb)

**Comment by liuxx479** [comment]
I am closing this issue too. Ok @EiffL ? Have you managed to download the maps?
