### ISSUE TITLE
Generate training convergence maps from kappaTNG

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/jax-lensing#13]
This issue is to track the development of a TensorFlow Dataset tool for reading the kappaTNG data, and setup the tools to draw maps appropriate for training a prior for COSMOS reconstruction.

- [x] : Add a kappaTNG dataset 
- [x] : Prototype JAX batch generation function including various on-the-fly data augmentation 

This second task also involves deciding what size of field we want to reconstruct, and at what pixel resolution.

**Comment by EiffL** [comment]
@b-remy is already working on this in branch `kappatng-dataset`

**Comment by EiffL** [comment]
Can you document here the status of this issue?

**Comment by b-remy** [comment]
At this point, we have:
- a script that generate the kappatng tensorflow dataset `datasets/kappatng.py`,
- the data in the common folder `tensorflow_datasets`,
- a tool function to load the dataset and do preprocessing (cropping to 320*320, flipping, noise corruption) on batches (`utils.py`).

Now that we have bigger images (1024^2), we may want to have a bigger cropping...

**Comment by b-remy** [comment]
I think this issue is solved with the last post, so I attached the pull request.

I also added a [notebook](https://github.com/CosmoStat/jax-lensing/blob/kappatng-dataset/notebooks/KappaTNG_COSMOS_emulation.ipynb) to emulate the COSMOS field with the kappaTNG dataset.

Could you check that especially these lines are still relevant ?
```
ngal_cosmos = 8 # This how many galaxies we have in real cosmos data
sigma_noise = 0.15*sqrt(8)/sqrt(30) # We have a noise of 0.15 in real data
print("effective noise per pixel and components:", sigma_noise )
# we can also include reduced shear
g1 = e1 / (1 - k)
g2 = e2 / (1 - k)
```

**Comment by EiffL** [comment]
ah, I remember.... I think.. This :
```python
sigma_noise = 0.15*sqrt(8)/sqrt(30)
```
Is just to tune the amount of noise to a different number of galaxies per sq. arcmin. We don't need it in our case. If we just want to reproduce the noise from the data, we should just use 0.15, or whatever the equivalent is for your new catalog.

**Comment by b-remy** [comment]
Ok, now real and mock COSMOS shear maps have the same amount of noise (see the [notebook](https://github.com/CosmoStat/jax-lensing/blob/kappatng-dataset/notebooks/KappaTNG_COSMOS_emulation.ipynb)) :)
