### ISSUE TITLE
Add tool to insert NFW profile on shear maps

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/jax-lensing#16]
For testing purposes, we would like to be able to insert the lensing signal for a cluster of a given S/N (or mass, concentration, redshift) artificially into a shear map.

The tasks here would be:
- [ ] : add an NFW lensing function that can return shear or convergence for a profile at given mass, redshift, concentration
- [ ] : add unit tests

For what it's worth, the NFW profile lensing signal can be found in various places, here is my favorite one:
https://arxiv.org/pdf/astro-ph/0304034.pdf

**Comment by EiffL** [comment]
https://github.com/CosmoStat/lenspack/blob/master/lenspack/halo/profiles.py

**Comment by EiffL** [comment]
Our goal here is to add a function with the following interface:

```python
def gen_NFW_shear( x_cen, y_cen, pixel_scale, nx, ny, z, mass,  redshift_distribution=None, zs=None, como=None):
   """
   returns: a map g1,g2 of size [nx,ny]
   """
```

**Comment by b-remy** [comment]
At this point I create shear field from a NFW profile and check with convergence after KS93 transformation:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/30293694/109322301-6e69a200-7852-11eb-857d-9d6b3ac9f313.png">

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/30293694/109322284-67429400-7852-11eb-952d-7ac97480753d.png">

But I think the error is too high, I'll investigate deeper

**Comment by EiffL** [comment]
Hi @b-remy , do you have updates on this :-) ?

**Comment by b-remy** [comment]
Hi @EiffL , yes I made some experiments :)

Few updates on the code:
- The code that generates the NFW profile above is in [`jax_lensing/cluster.py`](https://github.com/CosmoStat/jax-lensing/blob/map-script/jax_lensing/cluster.py).
- In a new script [`scripts/sample_cluster.py`](https://github.com/CosmoStat/jax-lensing/blob/map-script/scripts/sample_cluster.py), a NFW profile is added on a shear map and we sample from the posterior distribution given the noisy shear.
- Notice that the sampling procedure can be easily replaced since we now only call `from jax_lensing.samplers.procedures import tempered_HMC`

For the first experiment I added a NFW profile with parameters:
```python
x_cluster=100
y_cluster=100
z_halo=.5
mass_halo=2e15
zs=1
```
Here is how the target convergence is changed with the added cluster:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/30293694/117110616-b3481280-ad86-11eb-9d64-b9f410cb243a.png">

The sampling is done at three different noise levels in the shear maps (`0.07`, `0.148` similar to COSMOS and `0.21`), bellow are displayed cutouts of the cluster region:

`sigma = 0.07`:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/30293694/117110998-42edc100-ad87-11eb-95e7-9b2abe3bc48e.png">

`sigma = 0.148`:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/30293694/117111079-631d8000-ad87-11eb-9912-8ef7aead8a06.png">

`sigma = 0.21`:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/30293694/117111440-e3dc7c00-ad87-11eb-9340-031dad5ce603.png">

At noise levels `0.07` and `0.148`, it is not clear to me that the posterior is bimodal, but I think that the mass of the cluster is to high. So I launched other experiments with `mass_halo=3e14`.

I am also going to plot histograms of the stamps and compare them at different level of noise.

**Comment by EiffL** [comment]
Very very interesting!!! Quick question, are the colorscales the same on all plots?

**Comment by EiffL** [comment]
If the colorscales are different, I assume what we are seeing is that the cluster is becoming fainter when the noise increasing

**Comment by b-remy** [comment]
> are the colorscales the same on all plots?

No they weren't but in the following there are!

> I assume what we are seeing is that the cluster is becoming fainter when the noise increasing

Yes, but as the mass of the cluster was very high, so was its SNR and thus data were too much constraining to have a bimodal posterior.

So I decreased the cluster mass to `3e14` solar mass. Again, bellow are displayed cutouts of the cluster region (with same colorscale! i.e. in `[-0.05, 0.3]`).

`sigma = 0.07`:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/30293694/117182968-490b8e00-add7-11eb-8387-fa1a9a6b090e.png">

`sigma = 0.148`:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/30293694/117182945-414be980-add7-11eb-880e-bedb52db1e69.png">

`sigma = 0.21`:
<img width="785" alt="image" src="https://user-images.githubusercontent.com/30293694/117183074-6b9da700-add7-11eb-9513-229f60dc72f3.png">

Then, as we discussed I plotted the histogram of the cutouts statistics. Each cutout is summed up by its mean and added to the histogram at a given SNR (cutouts of size 6x6).

What I think we can observe is that the higher the SNR, the more we get high intensity cutouts (so with presence of the cluster). With the increase of SNR, there is a right-shift of the intensity distribution that could represent a "shift of the weight of the posterior modes". Not sure to stand it clearly ^^' The posterior is multimodal but at higher SNR the mode corresponding to presence of cluster would get more weight.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/30293694/117185062-b8827d00-add9-11eb-8ce5-ee043b340be5.png">

**Comment by EiffL** [comment]
Ahah ! Nice!!!
We got some blinking happening!

Ok so, if I understand correctly, you are averaging the entire stamp, which is larger than the cluster, so you are going to capture more than the signal from the cluster itself and it will make the measurement noisy.

One way to get a cleaner measure of the reconstructed cluster signal is to do some sort of "matched filtering", i.e. you apply a filter to the stamp based on your knowledge of the true cluster profile.
Here, you could simply do a weighted average of the postage stamp, using the true cluster profile as your window function.
This should suppress the parts of the image that are not the cluster and give you a cleaner measurement.

**Comment by EiffL** [comment]
You can plot a vertical line to indicate what is the true value of the cluster convergence in the ground truth map

**Comment by b-remy** [comment]
> One way to get a cleaner measure of the reconstructed cluster signal is to do some sort of "matched filtering", i.e. you apply a filter to the stamp based on your knowledge of the true cluster profile.

Following your advice, the weighted average of the postage stamp makes indeed the measurement very much less sensitive to the window size. The average of the stamp *S* is computed with the cluster stamp *Kappa_NFW* as:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/30293694/117296883-d8677e80-ae75-11eb-959d-4f759dfea519.png">

Finally, here are the result with different window sizes:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/30293694/117297131-241a2800-ae76-11eb-8498-ae81449f3365.png">

<img width="768" alt="image" src="https://user-images.githubusercontent.com/30293694/117297189-385e2500-ae76-11eb-9424-eac7bde13083.png">

<img width="780" alt="image" src="https://user-images.githubusercontent.com/30293694/117297323-5fb4f200-ae76-11eb-8eeb-87942a62a208.png">

**Comment by EiffL** [comment]
ok this is really cool :-) hummmmmm... I'm wondering how we can get a cleaner plot...

There is something that is usually important to look at, it's the "background" distribution, i.e. what this histogram looks like if you in fact don't have a cluster in the field. The behavior we should be able to see is that at low SNR the distribution should collapse to the background distribution.

**Comment by b-remy** [comment]
Ok, I am going to sample maps without cluster to compare histograms

**Comment by EiffL** [comment]
I added a very ugly notebook ^^' but it demonstrates roughly the approach we can take. Notebook is here: https://github.com/CosmoStat/jax-lensing/blob/map-script/notebooks/test_detection.ipynb

So here are the steps:
- Step I: figure out an optimal filter for the detection of our cluster. For this, I use the aperture mass filter from lenspack, and make a plot of SNR vs smoothing radius of the central pixel of the filtered postage stamps, using the standard deviation of filterd backgrounnd stamps as my "noise level"
![image](https://user-images.githubusercontent.com/861591/120931993-482a8c80-c6f4-11eb-9c4f-4234451879d4.png)
So, I see that with a smoothing scale between 6 and 8 pixels, we get a nice detection in the mean map. 
So I fix this choice of filter and smoothing scale

- Step II: Comparing the histograms of background pixels in filtered map vs hihstogram of center pixels, and I get this histogram:
![image](https://user-images.githubusercontent.com/861591/120932081-abb4ba00-c6f4-11eb-8266-5cdaa39f84b1.png)
(x axis is roughly normalized to k sigma)
So,  I see that if I set a threshold at 5 sigma I reject all background pixels. 

- Step III: I set my detection threshold to 5 sigma, and I compare the number of times I detect an object in map vs number of times I dont:
![image](https://user-images.githubusercontent.com/861591/120932140-f0d8ec00-c6f4-11eb-8fe7-f759c0b4d61f.png)
And this tells me that the cluster is detected in the posterior 77% of the time. 

I can also grab stamps that corresponds to detections and non-detections:
![image](https://user-images.githubusercontent.com/861591/120932183-149c3200-c6f5-11eb-839f-7b3176a88097.png)
![image](https://user-images.githubusercontent.com/861591/120932191-18c84f80-c6f5-11eb-8c29-ecdd49ca5a02.png)

**Comment by EiffL** [comment]
So.... next step is: given a choice of a fixed detection strategy (for instance the one I have chosen here), what does a plot of input cluster SNR vs detection frequency looks like?

This is what @jstarck wants  to know I think
