### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/jax-lensing#18]
Our current README is completely empty, this makes me sad. What makes me very happy are badges! 

I'm opening this issue to remind ourselves to add links to publications, youtube videos, tests, etc, all that good stuff in the README. 

Also install instructions and such.

**Comment by EiffL** [comment]
Here is a README I did and that I like :-) 
https://github.com/DifferentiableUniverseInitiative/jax_cosmo/blob/master/README.md

**Comment by EiffL** [comment]
and.... where is my cool README >.< ???? @b-remy

**Comment by b-remy** [comment]
Hi @EiffL , I just made a first draft that you can visualize [here](https://github.com/CosmoStat/jax-lensing/tree/doc) :-)

Feel free to make suggestions!

**Comment by b-remy** [comment]
The annealing gif is for preview, but I'm going to make another one with white background.

**Comment by EiffL** [comment]
Nice !

You want a few badges as well ;-)

**Comment by NiallJeffrey** [comment]
This is amazing!

**Comment by EiffL** [comment]
nice indeed this readme, but I notice you added an all-contributor badge manually  I think.

all-contributors is a github bot, and set of guidelines, to recognize all contributions made to a project. It is indeed very nice to have :-) But I would suggest using the official bot, that makes things a lot simpler:

check this out:
https://allcontributors.org/

**Comment by EiffL** [comment]
@all-contributors add @b-remy for code

**Comment by EiffL** [comment]
@all-contributors please add @b-remy for infrastructure, tests and code

**Comment by EiffL** [comment]
;-)

**Comment by b-remy** [comment]
@all-contributors please add @EiffL for infrastructure, tests and code.

**Comment by b-remy** [comment]
@all-contributors please add @NiallJeffrey  for tests and code.

**Comment by b-remy** [comment]
@all-contributors please add @liuxx479 for tests and code.
