### ISSUE TITLE
Adapt scripts to be able to use KappaTNG dataset

### ISSUE THREAD

**Issue by b-remy** [CosmoStat/jax-lensing#21]
Here we only need to adapt `train_mnu_score.py` and `sample_maps.py` and enable the choice of dataset.

Since there are common methods, I think that it would be smarter to put them in the `jax_lensing` folder. Such as `log_gaussian_prior`, `score_fn`, etc. Moreover I think it will ease the documentation process.

**Comment by b-remy** [comment]
We are thinking at downsizing our images to 320x320 again. However, the new dataset kappaTNG's resolution is 0.29 arcmin/pixel so for the same region of the sky the signal has a larger overlap in the image:
![res0 29width320](https://user-images.githubusercontent.com/30293694/105888302-19492f00-600d-11eb-927d-e7d2c92518b4.png)

@EiffL, do you think we still have enough padding, in order to avoid artefacts due to the FFT?

**Comment by EiffL** [comment]
hummmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by EiffL** [comment]
that's not a lot of padding left :-/ I would have preferred a bit more, maybe 360x360? that's 20 more pixels on each side, would pretty  much double the buffer area?

**Comment by b-remy** [comment]
360x360 would give these maps. I agree it would double the buffer area
![resolution0 29width360](https://user-images.githubusercontent.com/30293694/105896160-bfe5fd80-6016-11eb-8b08-6d837212758b.png)

**Comment by EiffL** [comment]
Yes, ok :-) I think this looks reasonable now. I hope it will fit in memory ^^

**Comment by b-remy** [comment]
It fits up to `batch_size=29`... So maybe using 2 gpus will enable training with `batch_size=32` and `360x360` maps.

**Comment by b-remy** [comment]
So do you allow a multi-gpu training? With the new dataset we can't reduce map size and we don't want to reduce batch size...

**Comment by EiffL** [comment]
hummmmmmm..... I would rather either trim a little bit the image, simplify the network, or keep the batch size at 29.....

If you want to do multi-gpu training, it's not "presse-boutton" ^^", it's explained here for haiku: https://github.com/deepmind/dm-haiku#distributed-training-with-jaxpmap
But if it is what is needed.... then yeah I guess.

**Comment by EiffL** [comment]
did this work?

**Comment by b-remy** [comment]
I did a full training yesterday with a batch size of 28 on one gpu, today I'm looking at the results
