### ISSUE TITLE
Writing section on Simulations and Data

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/jax-lensing#30]
This issue is to track discussions on the data and sims sections of the paper. At present, this should be in section 4.
We essentially need the following:

- [ ] : Description of kappa-TNG simulations. @liuxx479 would you be able to add text on that in section 4.1?
- [ ] : Describe the COSMOS sample we got from Tim. @EiffL can do that in section 4.2
- [ ] : Describe how we build convergence maps that match the redshift distribution of the cosmos sample. @b-remy I think you had plots for this, and maybe @liuxx479 can also add some text on how you produced the final convergence maps? This I think can go in section 4.3

**Comment by liuxx479** [comment]
done 4.1; seems like 4.3 is been written too.

**Comment by EiffL** [comment]
Thank you so much Jia!
