### ISSUE TITLE
HMC before SDE sampler

### ISSUE THREAD

**Issue by b-remy** [CosmoStat/jax-lensing#49]
I fixed the HMC sampler to run chains by batch in #47.

I made a comparison of sampling with and without running HMC at high temp before the SDE sampler in [sampler_maps.py](https://github.com/CosmoStat/jax-lensing/blob/paper-nb/scripts/sample_maps.py).

Here is a movie of the comparison. With the setting I used, I think it does not help to get a higher variety in the data region...

https://user-images.githubusercontent.com/30293694/130820078-553e210e-38a1-4b21-906c-e1d086e0663b.mp4

**Comment by b-remy** [comment]
Same kind of animation showing the temperature cooling down :-D

https://user-images.githubusercontent.com/30293694/131469945-7763b411-02eb-42d0-b05c-9fb7a5605de8.mp4

**Comment by EiffL** [comment]
Hi @b-remy I'm giving a talk tomorrow where I'm talking about this project and wanted to include a video. Do you have a more recent version of the first video in this thread? Showing posterior samples flickering.

No worries at all if you don't have one handy ^^

**Comment by EiffL** [comment]
right now I've cut out the left part of top plot:
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/861591/135535524-10ae1369-7ab8-4ed0-9cd8-2ee998367581.gif)

**Comment by b-remy** [comment]
I have another one with a higher initial temperature but I'm not sure it will be better than your cut out :) also you can see that on some samples it appears some unexpected large signals outside the masked region

https://user-images.githubusercontent.com/30293694/135537583-65b8daa1-de1f-47d2-b37b-427df58d21cb.mp4

Did you have something else in mind?

**Comment by EiffL** [comment]
Yeah that's what I was thinking about. But my gif is similar yeah

**Comment by b-remy** [comment]
Video of posterior samples updated with the last sampling script:

https://user-images.githubusercontent.com/30293694/143606768-6b7a45fe-ef14-432a-97a5-2c6269294776.mp4
